logging:
  level:
    ROOT: INFO
    de.dev.eth0: INFO


app:
  files:
    planets: data/data_planets.csv
    resources: data/data_resources.csv
    planetary_resources: data/dlinks_planetary_resources.csv


spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
